-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.audit_log
(
    audit_id uuid NOT NULL,
    actor_usuario_id uuid,
    entidad character varying COLLATE pg_catalog."default" NOT NULL,
    entidad_id uuid,
    accion character varying COLLATE pg_catalog."default" NOT NULL,
    detalle jsonb,
    ip character varying COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone,
    CONSTRAINT audit_log_pkey PRIMARY KEY (audit_id)
);

CREATE TABLE IF NOT EXISTS public.offline_sync
(
    sync_id uuid NOT NULL,
    usuario_id uuid,
    payload jsonb NOT NULL,
    status sync_status,
    created_at timestamp without time zone,
    processed_at timestamp without time zone,
    CONSTRAINT offline_sync_pkey PRIMARY KEY (sync_id)
);

CREATE TABLE IF NOT EXISTS public.red_empresa
(
    red_id uuid NOT NULL,
    sede_id uuid,
    nombre_red character varying COLLATE pg_catalog."default" NOT NULL,
    tipo tipo_red,
    ssid character varying COLLATE pg_catalog."default",
    bssid character varying COLLATE pg_catalog."default",
    ip_publica character varying COLLATE pg_catalog."default",
    activa boolean,
    CONSTRAINT red_empresa_pkey PRIMARY KEY (red_id)
);

CREATE TABLE IF NOT EXISTS public.registro_asistencia
(
    registro_id uuid NOT NULL,
    usuario_id uuid,
    sede_id uuid,
    tipo tipo_asistencia,
    timestamp_registro timestamp without time zone,
    latitud character varying COLLATE pg_catalog."default",
    longitud character varying COLLATE pg_catalog."default",
    dentro_geocerca boolean,
    modo modo_registro,
    device_info jsonb,
    evidence character varying COLLATE pg_catalog."default",
    ip_detectada character varying COLLATE pg_catalog."default",
    ssid_detectada character varying COLLATE pg_catalog."default",
    bssid_detectada character varying COLLATE pg_catalog."default",
    CONSTRAINT registro_asistencia_pkey PRIMARY KEY (registro_id)
);

CREATE TABLE IF NOT EXISTS public.reveal_requests
(
    reveal_id uuid NOT NULL,
    solicitante_id uuid,
    motivo character varying COLLATE pg_catalog."default" NOT NULL,
    timestamp_solicitud timestamp without time zone,
    CONSTRAINT reveal_requests_pkey PRIMARY KEY (reveal_id)
);

CREATE TABLE IF NOT EXISTS public.sede
(
    sede_id uuid NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    latitud character varying COLLATE pg_catalog."default" NOT NULL,
    longitud character varying COLLATE pg_catalog."default" NOT NULL,
    radio_metros integer NOT NULL,
    direccion character varying COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT sede_pkey PRIMARY KEY (sede_id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    usuario_id uuid NOT NULL,
    documento character varying COLLATE pg_catalog."default" NOT NULL,
    nombre_real character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying COLLATE pg_catalog."default" NOT NULL,
    telefono character varying COLLATE pg_catalog."default",
    sede_id uuid,
    rol character varying COLLATE pg_catalog."default" NOT NULL,
    consentimiento_geolocalizacion boolean,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT usuario_pkey PRIMARY KEY (usuario_id),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT audit_log_actor_usuario_id_fkey FOREIGN KEY (actor_usuario_id)
    REFERENCES public.usuario (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.offline_sync
    ADD CONSTRAINT offline_sync_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.red_empresa
    ADD CONSTRAINT red_empresa_sede_id_fkey FOREIGN KEY (sede_id)
    REFERENCES public.sede (sede_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_asistencia
    ADD CONSTRAINT registro_asistencia_sede_id_fkey FOREIGN KEY (sede_id)
    REFERENCES public.sede (sede_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_asistencia
    ADD CONSTRAINT registro_asistencia_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reveal_requests
    ADD CONSTRAINT reveal_requests_solicitante_id_fkey FOREIGN KEY (solicitante_id)
    REFERENCES public.usuario (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_sede_id_fkey FOREIGN KEY (sede_id)
    REFERENCES public.sede (sede_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;